### PR TITLE
DotNetCompatibilityCheck: don't abort install on incompatible platform

### PR DESCRIPTION
**Pull request by apacker1**
If running NetCoreCheck.exe fails with error code ERROR_EXE_MACHINE_TYPE_MISMATCH or ERROR_BAD_EXE_FORMAT then don't abort the installation, just set the property to -1.  Fixes https://github.com/wixtoolset/issues/issues/7737

### CODE REVIEW

**Comment by apacker1** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by barnson** [comment]
Thanks. This looks good. We'll triage the issue at our meeting next week. My gut says `-1` is probably not the best value, just because of signs. I'm thinking 1 (+1) or 65535. Thoughts?

**Comment by apacker1** [comment]
Yeah, I wasn't sure about that.  I guess the main thing is that the value shouldn't be something that the NetCoreCheck.exe authors might use in the future, which I don't really know how to predict.  However, https://github.com/dotnet/deployment-tools/blob/main/src/clickonce/native/projects/NetCoreCheck/NetCoreCheck.h does make it look like any additional error codes will probably just increment from the current ones that are defined, around 0x3000.  So 65535 should be safe.  Maybe they could conceivably use +1 if they come up with some "successful, but ..." result code?  So I guess I'd vote for 65535, but I'm happy to do whatever you think is best.

**Comment by barnson** [comment]
Yeah, that was my thinking too. I left a comment on the issue so triage makes a recommendation.

**Comment by barnson** [comment]
Triage team says `13` is a good compromise of return value.

**Comment by apacker1** [comment]
@barnson OK, I've updated my code to use 13.  Also updated https://github.com/wixtoolset/web/pull/229 to reflect this change

**Comment by barnson** [comment]
Thanks!

**Pull request merged**
