### PR TITLE
Add a few more checks on rollback of Util User.

### PR DESCRIPTION
**Pull request by bevanweiss**
Add a few more checks on rollback of Util User.
~Tidy up the memory management around the ::NetUserGetInfo to align with MS guidance (https://learn.microsoft.com/en-us/windows/win32/api/lmaccess/nf-lmaccess-netusergetinfo#examples)~ 
Removed memory tidyup, it's now in the more recent PR #547

### CODE REVIEW

**Comment by bevanweiss** [comment]
I'm a little worried that the rollback tests for the Util User may not actually be functional.
When I uncomment the Assert's in ConfigureUsers, CreateUser and CreateUserRollback and run the rollback tests I'm only seeing the ConfigureUsers assert triggered.

My expectation was that all three would be triggered, the Configure would have setup the Create and the Rollback CAs, then the CreateUser should have triggered, Completed, then the CAFail would have triggered sometime later, which should have then resulted in the CreateUserRollback triggering.
Whilst the ConfigureUsers completes fine, neither of the other CAs appear to eventuate (in the ProductFail / ProductCommentFail tests).

**Comment by barnson** [comment]
Rollback is scheduled only in this if block:

    if ((USER_EXISTS_YES == ueUserExists) || (USER_EXISTS_INDETERMINATE == ueUserExists) || !(psu->iAttributes & SCAU_DONT_CREATE_USER))

**Comment by bevanweiss** [comment]
> Rollback is scheduled only in this if block:
> 
> ```
> if ((USER_EXISTS_YES == ueUserExists) || (USER_EXISTS_INDETERMINATE == ueUserExists) || !(psu->iAttributes & SCAU_DONT_CREATE_USER))
> ```

hmmm.... so in the Rollback Test (ProductFail / ProductCommentFail) I should not have expected CreateUser / CreateUserRollback to be executed?
I was really expecting to have CreateUser for each user (at least testName1 and testName2 which were to be created by the MSI).
And then post CAFail, I was expecting CreateUserRollback for each CreateUser that had actually modified state.

**Comment by barnson** [comment]
I haven't looked at the tests yet. I just remembered that User is different than a lot because rollback of a removal isn't possible.

**Review by robmen — APPROVED** [review]

**Pull request merged**
