### PR TITLE
Add support for non-SNI SSL certificate in WixToolset.Http

### PR DESCRIPTION
**Pull request by solidstore**
Added support for installing and binding an SSL certificate to an HTTP port.

Example:

```
        <Component>
            <File Source="example.txt" />
            <http:Certificate Id="SomeCertificate"
                              Name="Some Certificate"
                              StoreLocation="localMachine"
                              StoreName="my"
                              CertificatePath="[SOME_PATH]"
                              PFXPassword="[PFX_PASS]"/>
            <http:SslBinding Host="0.0.0.0" Port="8081" HandleExisting="fail">
                <http:CertificateRef Id="SomeCertificate" />
            </http:SslBinding>
        </Component>
```

### CODE REVIEW

**Comment by solidstore** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by barnson** [comment]
General feedback is that there's too much duplication, both between IIs cert CAs and the new cert CAs here and snisslcert.cpp and sslcert.cpp here. Can more of the tables be shared? That would help with code sharing.

**Comment by solidstore** [comment]
Agreed. I knew there was a lot of overlap. I'll refactor to share tables, however, when I tried this I couldnt find away to use a second extension during the unit tests.

**Comment by barnson** [comment]
@solidstore we're finalizing WiX v5 plans so if you want this in WiX v5, it needs to be done this month.

**Pull request closed without merging**
